### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by ELToulemonde** [ELToulemonde/dataPreparation#14]
A nice thing to build would be to make it usable from python.

Using rpy2 interface (?), it would be nice to be able call the package to prepare a data set and then go back to python using sklearn for example.

I don't know what form it should take: maybe a script or a tutorial.
A question would also be: what classes are accepted by pandas (i think of R class factor for example).

If anyone did something like that before, help would be more than appreciated :)

**Comment by coforfe** [comment]
Hi,

I would question this Python porting. 
There is already a library in Python for this:

https://pypi.org/project/feature-engine/
https://feature-engine.readthedocs.io/en/latest/

Well in fact, some of the ideas that I proposed to enhance your R package comes from this Python.

Thanks,
Carlos.

**Comment by ELToulemonde** [comment]
Hi,

Yes i guess you are right. THanks for the pointer. 

Do you know one that do the filtering as `dataPreparation` do (constant, double and bijection) ?
