### ISSUE TITLE
Problem installing package - Linux

### ISSUE THREAD

**Issue by PaulCristina** [ELToulemonde/dataPreparation#22]
Hi

When I try to install the package on my machine (Cent OS server), it gives me this error:
"Warning in fun(libname, pkgname) : couldn't connect to display ":0""

and when I try to use the library to convert all numerical variables
 DT <- findAndTransformNumerics(DT)
it gives me this error:
"Error in findAndTransformNumerics(DT1_first_launch_rewards) : 
  could not find function "findAndTransformNumerics"

On my windows machine it works fine so probably it's an error related to Linux?

Thanks
Paul

**Comment by ELToulemonde** [comment]
Hi,


I'm not sure that this issue comes from this package...
Can you give me more information? Which distribution, which R version, and the result of `sessionInfo()`

Also, in R, could you try to load `tcltk` package? 

Maybe [this question on stack](https://stackoverflow.com/questions/1710853/how-to-run-r-on-a-server-without-x11-and-avoid-broken-dependencies) this would help?


Concerning the second error, did you load `dataPreparation`? did it succeeded? 

---
Emmanuel-Lin

**Comment by PaulCristina** [comment]
It looks to be attached, I tried to load `tcltk`, it looks loaded but `dataPreparation` gives the same error

Session info below:


R version 3.4.1 (2017-06-30) Platform: x86_64-redhat-linux-gnu (64-bit) Running under: CentOS Linux 7 (Core)  Matrix products: default BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so  locale:  [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                  LC_TIME=C                     LC_COLLATE=C                   [5] LC_MONETARY=C                 LC_MESSAGES=C                 LC_PAPER=C                    LC_NAME=en_US.UTF-8            [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8      LC_MEASUREMENT=C              LC_IDENTIFICATION=en_US.UTF-8  attached base packages: [1] tcltk     stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] dataPreparation_0.2.1 Matrix_1.2-9          ggjoy_0.3.0           readr_1.1.1           mailR_0.4.1            [6] mgcv_1.8-17           nlme_3.1-131          rmarkdown_1.6         psych_1.7.5           tidyr_0.6.3           [11] dplyr_0.7.2           plyr_1.8.4            jsonlite_1.5          magrittr_1.5          tidyjson_0.2.2        [16] stringr_1.2.0         colortools_0.1.5      colorspace_1.3-2      ggthemes_3.4.0        viridis_0.4.0         [21] viridisLite_0.2.0     RColorBrewer_1.1-2    htmlwidgets_0.9       lubridate_1.6.0       knitr_1.14            [26] scales_0.5.0.9000     data.table_1.10.4     RMySQL_0.10.12        DBI_0.7               plotly_4.7.0          [31] ggplot2_2.2.1          loaded via a namespace (and not attached):  [1] Rcpp_0.12.12      lattice_0.20-35   assertthat_0.2.0  rprojroot_1.2     digest_0.6.12     mime_0.5           [7] R6_2.2.2          backports_1.1.0   evaluate_0.10.1   httr_1.3.1        rlang_0.1.2       lazyeval_0.2.0    [13] R.utils_2.5.0     R.oo_1.21.0       labeling_0.3      foreign_0.8-67    munsell_0.4.3     shiny_1.0.5       [19] compiler_3.4.1    httpuv_1.3.5      pkgconfig_2.0.1   mnormt_1.5-5      htmltools_0.3.6   tibble_1.3.4      [25] gridExtra_2.2.1   R.methodsS3_1.7.1 grid_3.4.1        xtable_1.8-2      gtable_0.2.0      formatR_1.5       [31] stringi_1.1.5     bindrcpp_0.2      tools_3.4.1       glue_1.1.1        purrr_0.2.3       hms_0.3           [37] crosstalk_1.0.0   parallel_3.4.1    yaml_2.1.14       rJava_0.9-8       bindr_0.1

Paul

**Comment by ELToulemonde** [comment]
Frankly, I have no idea on what could be the problem. 

Have you tried installing all dependecies by hand (to see if it is one of them that is failling)?

**Comment by ELToulemonde** [comment]
Can you check if the problem have been solved with the release of dataPreparation V0.3.2?

Thanks

**Comment by ELToulemonde** [comment]
No news... I close.
