### ISSUE TITLE
[New Feature]: Binning.... (Variable Discretization).

### ISSUE THREAD

**Issue by coforfe** [ELToulemonde/dataPreparation#23]
Hi Enmanuel,

It could be interesting also to add a new set of functionality in your package to dicretize variables. Most of the packages I know that include this feature are quite slow. So integrating `data.table` like your package could be a real advantage.

I remember seeing something similar in another package that finally did not progress to CRAN that could be a good reference to start with o even reuse their code. This other package is here:

[https://github.com/awstringer/modellingTools/blob/master/vignettes/modellingTools.md](url)

As you will see that project has been inactive for quite a long time... more than one year.

Well some ofther features that this package includes (descriptive statistics, etc) could be incorporated later to your package.

Thanks!
Carlos.

**Comment by ELToulemonde** [comment]
Hi Carlos,

Discrtization (equal freq and equal width) have been implemented in #28. 
I think that a way to apply discretization on a test set should be developped.


It will be available in next CRAN release. 


Cheers.

Emmanuel-Lin
