### ISSUE TITLE
Make dependency on tcl/tk optional

### ISSUE THREAD

**Issue by alexvorobiev** [ELToulemonde/dataPreparation#26]
tcl/tk is only used to display the progress bar. We have RStudio server (tk is not installed because we never establish X connections to the server) and the package is unusable. There are many packages such as https://github.com/r-lib/progress to create progress bars in text mode.
Thanks.

**Comment by ELToulemonde** [comment]
You are right.
I will do it as soon as i have some time.

**Comment by ELToulemonde** [comment]
Hi,

In #27 I replaced TCLTK by suggested library `progress`. It seems to work both on windows and linux environement. Could you control it on RStudio server?


It will be released on carn for the next relaease.

**Comment by alexvorobiev** [comment]
Thanks, the github version of the very useful package works now! I can use it in RStudio Server with no issues.

**Comment by ELToulemonde** [comment]
Sure, no problem.
I just pushed this version on CRAN so you should be able to install it directly from CRAN now.

If you have some new features ideas, please don't hesitate.
