### ISSUE TITLE
Not able to read mm/dd/yy dates correctly

### ISSUE THREAD

**Issue by Kaverisonu** [ELToulemonde/dataPreparation#34]
In the findAndTransformDates function of this package,i am not able to deal with dates having format 
mm/dd/yy.

My file has date like
1/1/2012
2/1/2012
3/1/2012
4/1/2012
5/1/2012
6/1/2012
7/1/2012
8/1/2012
9/1/2012
 which are getting read as 
2001-01-12
2002-01-12
2003-01-12
......

So basically the year and month part are getting exchanged here. Is there a way to tackle this already,or maybe i missed out the solution

**Comment by ELToulemonde** [comment]
Hi,

There is an ambiguity on your data...

There is no clear way to say if they are dd/mm/yyyy or mm/dd/yyyy this is why format is mistaken.

I take to points:

- This is weird that the year is also mistake... Could you provide a reproducible example?
- We could add a warning when we meet an ambiguity on data.


Thanks.

**Comment by Kaverisonu** [comment]
[Amazon.xlsx](https://github.com/ELToulemonde/dataPreparation/files/1588782/Amazon.xlsx)
[Amazon1.xlsx](https://github.com/ELToulemonde/dataPreparation/files/1588783/Amazon1.xlsx)

Attaching two files,one which s read correctly,and the other which does not read date correctly.

**Comment by ELToulemonde** [comment]
hi,

Thanks, by reproducible examples, I meant:

Take a few rows of your data.frame and perform `dput` so that I will have exactly the same format.
xlsx interpretation depends on your computer configuration.

**Comment by Kaverisonu** [comment]
If this helps..below is the format.

structure(list(Visits = c(11206L, 11652L, 12004L, 12497L, 12701L, 
19817L), Visits2 = c(14106L, 14552L, 14904L, 15397L, 15601L, 
22717L), Country = structure(c(1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Argentina", 
"Australia", "Canada", "Finland", "France", "Germany", "Hong kong", 
"Hong Kong", "India", "Italy", "Japan", "Mexico", "Netherlands", 
"New Zealand", "Singapore", "Sweden", "Taiwan", "Thailand", "UK"
), class = "factor"), channel = structure(c(3L, 3L, 3L, 3L, 3L, 
3L), .Label = c("Number of Posts", "Organic Reach", "Total Likes"
), class = "factor"), date = structure(c(1L, 5L, 9L, 13L, 17L, 
21L), .Label = c("01/01/12", "01/01/13", "01/01/14", "01/01/15", 
"02/01/12", "02/01/13", "02/01/14", "02/01/15", "03/01/12", "03/01/13", 
"03/01/14", "03/01/15", "04/01/12", "04/01/13", "04/01/14", "04/01/15", 
"05/01/12", "05/01/13", "05/01/14", "05/01/15", "06/01/12", "06/01/13", 
"06/01/14", "06/01/15", "07/01/12", "07/01/13", "07/01/14", "07/01/15", 
"08/01/12", "08/01/13", "08/01/14", "08/01/15", "09/01/12", "09/01/13", 
"09/01/14", "09/01/15", "10/01/12", "10/01/13", "10/01/14", "11/01/12", 
"11/01/13", "11/01/14", "12/01/12", "12/01/13", "12/01/14"), class = "factor"), 
    Visits3 = c(106L, 87L, 89L, 101L, 101L, 98L), spend = c(99L, 
    107L, 97L, 98L, 87L, 94L), Margin... = c(0.056, 0.057, 0.077, 
    0.03, 0.098, 0.067)), .Names = c("Visits", "Visits2", "Country", 
"channel", "date", "Visits3", "spend", "Margin..."), row.names = c(NA, 
6L), class = "data.frame")

**Comment by ELToulemonde** [comment]
Okay, I see...

You don't have dd/mm/yyyy but dd/mm/yy (17 for year instead of 2017). So it is impossible to know which one is day, month and year.
`findAndTranformDates` doesn't guess format with there is an ambiguity since we try to mak it as robust as possible. 

I would recommand you to try either:

- Increase `n_test` in `findAndTransformDates` (so that if you have days bigger than 12, ambiguity will be solved)
- Transform date by your self, since you know the format (using `setColAsDate` with `format = "%d/%m/%y"`)

Hope it helps.

**Comment by Kaverisonu** [comment]
The issue persists even if the data is loaded with 4-digit year.

structure(list(Visits = c(11206L, 11652L, 12004L, 12497L, 12701L, 
19817L), Visits2 = c(14106L, 14552L, 14904L, 15397L, 15601L, 
22717L), Country = structure(c(1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Argentina", 
"Australia", "Canada", "Finland", "France", "Germany", "Hong kong", 
"Hong Kong", "India", "Italy", "Japan", "Mexico", "Netherlands", 
"New Zealand", "Singapore", "Sweden", "Taiwan", "Thailand", "UK"
), class = "factor"), channel = structure(c(3L, 3L, 3L, 3L, 3L, 
3L), .Label = c("Number of Posts", "Organic Reach", "Total Likes"
), class = "factor"), date = structure(c(1L, 14L, 18L, 22L, 26L, 
30L), .Label = c("1/1/2012", "1/1/2013", "1/1/2014", "1/1/2015", 
"10/1/2012", "10/1/2013", "10/1/2014", "11/1/2012", "11/1/2013", 
"11/1/2014", "12/1/2012", "12/1/2013", "12/1/2014", "2/1/2012", 
"2/1/2013", "2/1/2014", "2/1/2015", "3/1/2012", "3/1/2013", "3/1/2014", 
"3/1/2015", "4/1/2012", "4/1/2013", "4/1/2014", "4/1/2015", "5/1/2012", 
"5/1/2013", "5/1/2014", "5/1/2015", "6/1/2012", "6/1/2013", "6/1/2014", 
"6/1/2015", "7/1/2012", "7/1/2013", "7/1/2014", "7/1/2015", "8/1/2012", 
"8/1/2013", "8/1/2014", "8/1/2015", "9/1/2012", "9/1/2013", "9/1/2014", 
"9/1/2015"), class = "factor"), Visits3 = c(106L, 87L, 89L, 101L, 
101L, 98L), spend = c(99L, 107L, 97L, 98L, 87L, 94L), Margin... = c(0.056, 
0.057, 0.077, 0.03, 0.098, 0.067)), .Names = c("Visits", "Visits2", 
"Country", "channel", "date", "Visits3", "spend", "Margin..."
), row.names = c(NA, 6L), class = "data.frame")

We need to dynamically read date variables(in any format,be it in any column),so transforming date by self option is not valid here.
n_test is by default 30?so as per my data,the 30 rows has sufficient dates to avoid ambiguity.

Don;t know if i am missing out something here.

**Comment by ELToulemonde** [comment]
With years on  4 digits: ambiguity as been solved for years. But you might still have an ambiguity on day and month. To solve ambiguity on day and month, you need to have at least one date with day > 12.

Indeed `n_test` is by default at 30. So you need to have one day > 12 in the first 30 lines, if it might be after, put it to a higher level.

**Comment by Kaverisonu** [comment]
The data normally can be in this form,since we want to see the trend on the monthly data for any 3 years,
so if the date is greater than 12, findAndTransformDates works,but here the data is of every 1st(it can be 2nd,3rd,....12th)  of each month(jan,feb,mar etc) where ambiguity is introduced.

So to summarize for mm/dd/yyyy format,
any date(dd) which lies between 1-12 would create ambiguity.

**Comment by Kaverisonu** [comment]
Thanks ELToulemonde!!!

I think after the 4-digit year are getting identified correctly,now i can specify the form for the reading the date as "%Y/%d/%m" and it can work.

**Comment by Kaverisonu** [comment]
Actually if the output format can be consistent after applying findAndTransformDates.

In case of my date format is as below,the output orders in yyyy/mm/dd,whereas in case of format being
mm/dd/yyyy(and any other format),the output orders in yyyy/dd/mm,can the output format atleast be consistent?So that i can use the output format to identify the order of date,month and year?

structure(list(Visits = c(11206L, 11652L, 12004L, 12497L, 12701L, 
19817L), Visits2 = c(14106L, 14552L, 14904L, 15397L, 15601L, 
22717L), Country = structure(c(1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Argentina", 
"Australia", "Canada", "Finland", "France", "Germany", "Hong kong", 
"Hong Kong", "India", "Italy", "Japan", "Mexico", "Netherlands", 
"New Zealand", "Singapore", "Sweden", "Taiwan", "Thailand", "UK"
), class = "factor"), channel = structure(c(3L, 3L, 3L, 3L, 3L, 
3L), .Label = c("Number of Posts", "Organic Reach", "Total Likes"
), class = "factor"), date = structure(c(16L, 12L, 28L, 1L, 32L, 
24L), .Label = c("1-Apr-2012", "1-Apr-2013", "1-Apr-2014", "1-Apr-2015", 
"1-Aug-2012", "1-Aug-2013", "1-Aug-2014", "1-Aug-2015", "1-Dec-2012", 
"1-Dec-2013", "1-Dec-2014", "1-Feb-2012", "1-Feb-2013", "1-Feb-2014", 
"1-Feb-2015", "1-Jan-2012", "1-Jan-2013", "1-Jan-2014", "1-Jan-2015", 
"1-Jul-2012", "1-Jul-2013", "1-Jul-2014", "1-Jul-2015", "1-Jun-2012", 
"1-Jun-2013", "1-Jun-2014", "1-Jun-2015", "1-Mar-2012", "1-Mar-2013", 
"1-Mar-2014", "1-Mar-2015", "1-May-2012", "1-May-2013", "1-May-2014", 
"1-May-2015", "1-Nov-2012", "1-Nov-2013", "1-Nov-2014", "1-Oct-2012", 
"1-Oct-2013", "1-Oct-2014", "1-Sep-2012", "1-Sep-2013", "1-Sep-2014", 
"1-Sep-2015"), class = "factor"), Visits3 = c(106L, 87L, 89L, 
101L, 101L, 98L), spend = c(99L, 107L, 97L, 98L, 87L, 94L), Margin... = c(0.056, 
0.057, 0.077, 0.03, 0.098, 0.067)), .Names = c("Visits", "Visits2", 
"Country", "channel", "date", "Visits3", "spend", "Margin..."
), class = c("data.table", "data.frame"), row.names = c(NA, -6L
), .internal.selfref = <pointer: 0x0000000003400788>)
structure(list(Visits = c(11206L, 11652L, 12004L, 12497L, 12701L, 
19817L), Visits2 = c(14106L, 14552L, 14904L, 15397L, 15601L, 
22717L), Country = structure(c(1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Argentina", 
"Australia", "Canada", "Finland", "France", "Germany", "Hong kong", 
"Hong Kong", "India", "Italy", "Japan", "Mexico", "Netherlands", 
"New Zealand", "Singapore", "Sweden", "Taiwan", "Thailand", "UK"
), class = "factor"), channel = structure(c(3L, 3L, 3L, 3L, 3L, 
3L), .Label = c("Number of Posts", "Organic Reach", "Total Likes"
), class = "factor"), date = structure(c(16L, 12L, 28L, 1L, 32L, 
24L), .Label = c("1-Apr-2012", "1-Apr-2013", "1-Apr-2014", "1-Apr-2015", 
"1-Aug-2012", "1-Aug-2013", "1-Aug-2014", "1-Aug-2015", "1-Dec-2012", 
"1-Dec-2013", "1-Dec-2014", "1-Feb-2012", "1-Feb-2013", "1-Feb-2014", 
"1-Feb-2015", "1-Jan-2012", "1-Jan-2013", "1-Jan-2014", "1-Jan-2015", 
"1-Jul-2012", "1-Jul-2013", "1-Jul-2014", "1-Jul-2015", "1-Jun-2012", 
"1-Jun-2013", "1-Jun-2014", "1-Jun-2015", "1-Mar-2012", "1-Mar-2013", 
"1-Mar-2014", "1-Mar-2015", "1-May-2012", "1-May-2013", "1-May-2014", 
"1-May-2015", "1-Nov-2012", "1-Nov-2013", "1-Nov-2014", "1-Oct-2012", 
"1-Oct-2013", "1-Oct-2014", "1-Sep-2012", "1-Sep-2013", "1-Sep-2014", 
"1-Sep-2015"), class = "factor"), Visits3 = c(106L, 87L, 89L, 
101L, 101L, 98L), spend = c(99L, 107L, 97L, 98L, 87L, 94L), Margin... = c(0.056, 
0.057, 0.077, 0.03, 0.098, 0.067)), .Names = c("Visits", "Visits2", 
"Country", "channel", "date", "Visits3", "spend", "Margin..."
), class = c("data.table", "data.frame"), row.names = c(NA, -6L
), .internal.selfref = <pointer: 0x0000000003400788>)

**Comment by ELToulemonde** [comment]
Hi,

So I tried to reconstruct your problem...

**Starting from this data set:**

```
structure(list(date = structure(c(16L, 12L, 28L, 1L, 32L, 24L
), .Label = c("1-Apr-2012", "1-Apr-2013", "1-Apr-2014", "1-Apr-2015", 
"1-Aug-2012", "1-Aug-2013", "1-Aug-2014", "1-Aug-2015", "1-Dec-2012", 
"1-Dec-2013", "1-Dec-2014", "1-Feb-2012", "1-Feb-2013", "1-Feb-2014", 
"1-Feb-2015", "1-Jan-2012", "1-Jan-2013", "1-Jan-2014", "1-Jan-2015", 
"1-Jul-2012", "1-Jul-2013", "1-Jul-2014", "1-Jul-2015", "1-Jun-2012", 
"1-Jun-2013", "1-Jun-2014", "1-Jun-2015", "1-Mar-2012", "1-Mar-2013", 
"1-Mar-2014", "1-Mar-2015", "1-May-2012", "1-May-2013", "1-May-2014", 
"1-May-2015", "1-Nov-2012", "1-Nov-2013", "1-Nov-2014", "1-Oct-2012", 
"1-Oct-2013", "1-Oct-2014", "1-Sep-2012", "1-Sep-2013", "1-Sep-2014", 
"1-Sep-2015"), class = "factor")), .Names = "date", row.names = c(NA, 
-6L), class = c("data.table", "data.frame"))
```

**NB:** I simpliied it by keeping only date column.


**You want to identify dates:**

Since format is pretty obvious, findAndTransformDates perform it weel:

```
dataSet = findAndTransformDates(dataSet)
[1] "findAndTransformDates: It took me 0.25s to identify formats"
[1] "findAndTransformDates: It took me 0.02s to transform 1 columns to a Date format."
dataSet
         date
1: 2012-01-01
2: 2012-02-01
3: 2012-03-01
4: 2012-04-01
5: 2012-05-01
6: 2012-06-01
```

You now have YYYY/MM/DD which is what you expected.

Please note, that now format is in POSIXct which is one of R date format. 

Just to control, one might check:
```
month(dataSet$date)
[1] 1 2 3 4 5 6
```

Which show you that month  are 1, 2, 3, 4, 5, 6... conresponding to jan, feb, march...


**Your other problem:**

Starting fromat data set:
```
dataSet = structure(list(date = c("01/01/2012", "02/01/2012", "03/01/2012", 
"04/01/2012", "05/01/2012", "06/01/2012")), .Names = "date", row.names = c(NA, 
-6L), class = c("data.table", "data.frame"))
```

Then you perform:

```
dataSet = findAndTransformDates(dataSet)
[1] "findAndTransformDates: It took me 0.23s to identify formats"
[1] "findAndTransformDates: It took me 0.02s to transform 1 columns to a Date format."
dataSet
         date
1: 2012-01-01
2: 2012-01-02
3: 2012-01-03
4: 2012-01-04
5: 2012-01-05
6: 2012-01-06
```

Which seems, to have work, but didn't do what you have expected:

```
month(dataSet$date)
[1] 1 1 1 1 1 1
```

Every month is 1, because there where an ambiguity in your data (betwwen format %Y/%m/%d and %Y/%d/%m. One have been chosen, but you are out of luck it's not the good one.


**Conclusion:**

- There are two types of ambiguities: 
  - On Years if they are in format yy
  - On Month/day if there isn't any day higher than 12 in the first `n_test` lines
- Format in output of `findAndTransformDates` is always the same: POSIXct
- `findAndTransformDates` should raise a warning when there is an ambiguity, it will be developped in next version.




Did I answer all of your questions?

Thanks.

**Comment by Kaverisonu** [comment]
Thanks a lot!!

Sounds good

**Comment by ELToulemonde** [comment]
Okay, then I close.

Thanks for your questions.
