### ISSUE TITLE
Scale Back

### ISSUE THREAD

**Issue by dotRData** [ELToulemonde/dataPreparation#36]
we have function "fastScale" to use "build_scales" and transform the data to standardise it.
is there another function which scales back the transformed variable ?

as your code is written on references, most of your functions changes the original object.

**Comment by ELToulemonde** [comment]
Yes it is the main goal... to work by reference to avoid copying object in RAM.

In which cases would you need to reverse it?

**Comment by dotRData** [comment]
If I want to analyse some relation between the predicted values and some other columns in the dataset. For example: correlation between 2 variable will not change, but RMSE will.

newTestData <- fastScale(copy(testData), scaleTrain)

I am currently using something like this to keeping track of old data as well, which is not very efficient for handling bigger dataset. 

In general, we just need to scale variable just for faster and better results. And original values will be needed during post-Model Analysis and presentation.

**Comment by ELToulemonde** [comment]
Ok I see.

How would you see it? 
An additionnal parameter to `fastScale` to reverse it? 
Or another function `fastUnScale` to unscale?

**Comment by dotRData** [comment]
I guess, `fastUnScale` would be a better way to handle it. Thanks :)

**Comment by ELToulemonde** [comment]
Hmmm... I'm not sure, for factorization purpouse I would tend to use the other way...

Why do you prefer this one?

Do you have time to try to developp it?

**Comment by dotRData** [comment]
I can help you in developing it, But i thought it would be easy ...

just by changing this 
`set(dataSet, NULL, col, (dataSet[[col]] - scales[[col]][["mean"]]) / scales[[col]][["sd"]])`
to
`set(dataSet, NULL, col, (dataSet[[col]] * scales[[col]][["sd"]]) + scales[[col]][["mean"]])`
 
in the new function.

**Comment by ELToulemonde** [comment]
Yep, that would be that for the code .
+ There is the documentation
+ Unit test
+ Devtools checks

Even if it sound simple it take some time and any help would be much appriciated :)

**Comment by dotRData** [comment]
Yes, I can help you with that. I don't have, much experience in writing package. 
I had to start somewhere, will learn something new in the process.

Will create a fork and send you the pull request this weekend. :)

**Comment by ELToulemonde** [comment]
Ok thanks. 

Here are some recommandation on how to proceed:

1. Build new function in the best R file (here i guess in scale file)
2. Document function. Make sure every param is commented. 
3. Change package version in DESCRIPTION and add what's new in NEWS.md
3. Build unit tests in tests\testthat\test_.....R (one test file per R code file). Unit test should make sure that your function works exactly the way you want it.
4. Generate documentation using devtools::document() and control unit tests using devtools::test()
5. Build and install package using devtools::build(), devtools::install()
6. Control that every thing is conform to CRAN requirement using devtools::check(pkg = "dataPreparation"). You should have no error, no warning and no notes.
7. Push on github and travis will check if everything is ok. There would also be a code coverage control.
8. If everything passed: create a Pull Request

If you need any help, more details, don't hesitate.

Many thanks.

**Comment by dotRData** [comment]
> devtools::check(pkg = "dataPreparation")
Updating dataPreparation documentation
Loading dataPreparation
Loading required package: lubridate

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

Loading required package: stringr
Loading required package: Matrix
Loading required package: progress
Setting env vars --------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building dataPreparation ------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build '/Users/ranand/dataPreparation'  \
  --no-resave-data --no-manual

* checking for file ‘/Users/ranand/dataPreparation/DESCRIPTION’ ... OK
* preparing ‘dataPreparation’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
**Warning: ‘inst/doc’ files
    ‘dataPreparation.Rmd’, ‘train_test_prep.Rmd’,  ‘dataPreparation.html’, ‘train_test_prep.html’, ‘dataPreparation.R’,  ‘train_test_prep.R’
  ignored as vignettes have been rebuilt.**
  Run R CMD build with --no-build-vignettes to prevent rebuilding.
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘dataPreparation_0.3.6.tar.gz’
**Warning: invalid uid value replaced by that for user 'nobody'
Warning: invalid gid value replaced by that for user 'nobody'**

Setting env vars --------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking dataPreparation ------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/rw/zl99_kys3hd_yk_ykl5rfg513lyd55/T//RtmpAou6uI/dataPreparation_0.3.6.tar.gz'  \
  --as-cran --timings --no-manual

* using log directory ‘/private/var/folders/rw/zl99_kys3hd_yk_ykl5rfg513lyd55/T/RtmpAou6uI/dataPreparation.Rcheck’
* using R version 3.4.3 (2017-11-30)
* using platform: x86_64-apple-darwin15.6.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘dataPreparation/DESCRIPTION’ ... OK
* this is package ‘dataPreparation’ version ‘0.3.6’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘dataPreparation’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
Examples with CPU or elapsed time > 5s
                        user system elapsed
generateFactorFromDate 6.799  0.152   7.033
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ [161s/161s]
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* DONE

Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes

**Comment by dotRData** [comment]
there seems to be 3 warning in between.
does it looks ok ?

**Comment by ELToulemonde** [comment]
Since user didn't provide any news, feature has been implemented in v0.3.5 by adding a *way* parameter to function `fastScale`.

Will soon be pushed on CRAN.

Thanks for the request for new feature.

I close
