### ISSUE TITLE
[New Feature]: Transform dates in numeric.

### ISSUE THREAD

**Issue by coforfe** [ELToulemonde/dataPreparation#9]
Hello Enmanuel,

Another possible transformation would be to move from dates to integers.
The alternatives I am thinking of are:
- Count the number of days between a date in the past to each date.
- Count the number of days between each date in the data.frame and todays date.

Is an equivalent to the high cardinality transformation for string. 
These transformations would happen after unifying the formats as you have already considered in `findAndTransformDates` function.

Thanks,
Carlos.

**Comment by ELToulemonde** [comment]
Hello Carlos,

Thanks for your input, 

I don't know if i understood you well, but I think this feature, is already available using `diffDates` function, and feeding an `analysisDate`, either a date in the past or today's date.

Emmanuel-Lin

**Comment by coforfe** [comment]
Hello Enmanuel-Lin,

Sorry for not giving feedback to you sooner...
Yes, I saw that this kind of transformation was already available in your package.

On top of that, besides the enhancement I suggested, I am seeing if other ideas I had are already present in this other package that has a similar goal as yours:

[https://github.com/ben519/mltools](https://github.com/ben519/mltools)

Thanks,
Carlos.

**Comment by ELToulemonde** [comment]
Hi Carlos,

RThanks a lot for this link!  Indeed there are some interesting features in this package, and it also gave me some ideas for some new features.

I open a project to follow all those enhancements

Cheers

Emmanuel-Lin
